app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/com/futurice/android/reservator/LoginActivity.java, app/src/main/java/com/futurice/android/reservator/view/trafficlightsactivity/TrafficLightsActivity.java, app/src/main/res/layout/traffic_lights_activity.xml, app/src/main/res/values/colors.xml, build.gradle
Added dummy TrafficLightsActivity. This will be the main activity in the future.
=> added dummy TrafficLightsActivity

app/src/main/java/com/futurice/android/reservator/view/CalendarVisualizer.java, app/src/main/java/com/futurice/android/reservator/view/WeekView.java, app/src/main/java/com/futurice/android/reservator/view/trafficlights/DayCalendarFragment.java, app/src/main/java/com/futurice/android/reservator/view/trafficlights/TrafficLightsPageFragment.java, app/src/main/java/com/futurice/android/reservator/view/trafficlights/TrafficLightsPresenter.java, app/src/main/res/layout-v17/room_reservation_fragment.xml, app/src/main/res/layout/day_calendar_fragment.xml, app/src/main/res/layout/traffic_lights_page_fragment.xml
Adds day calendar to the traffic lights page. This is not that pretty yet, but seems to work. TODO: number of days to show needs to be made a parameter, currently it is a hardcoded value in both WeekView and CalendarVizualizer.
=> Add day calendar

app/src/main/AndroidManifest.xml, app/src/main/java/com/futurice/android/reservator/CalendarStateReceiver.java, app/src/main/java/com/futurice/android/reservator/MainActivity.java
This is a fix for issue #27 and will complete issue #20
=> Fix crash when calendar updated

app/src/main/java/com/futurice/android/reservator/view/trafficlights/OngoingReservationFragment.java, app/src/main/java/com/futurice/android/reservator/view/trafficlights/TrafficLightsPageFragment.java, app/src/main/java/com/futurice/android/reservator/view/trafficlights/TrafficLightsPresenter.java, app/src/main/res/layout-v17/ongoing_reservation_fragment.xml, app/src/main/res/layout/traffic_lights_page_fragment.xml, app/src/main/res/values/strings.xml
Added OngoingReservationFragment for modifying ongoing reservations. No functionality yet.
=> Added OngoingReservationFragment with no functionality

app/src/main/java/com/futurice/android/reservator/view/trafficlights/OngoingReservationFragment.java, app/src/main/java/com/futurice/android/reservator/view/trafficlights/TrafficLightsPresenter.java, app/src/main/res/layout-v17/ongoing_reservation_fragment.xml, app/src/main/res/values/strings.xml
OngoingReservationFragment now updates its seekbar according to remaining reservation minutes
=> OngoingReservationFragment now updates its seekbar

app/src/main/java/com/futurice/android/reservator/view/trafficlights/BottomFragment.java, app/src/main/java/com/futurice/android/reservator/view/trafficlights/TrafficLightsPageFragment.java, app/src/main/res/layout/bottom_fragment.xml, app/src/main/res/layout/traffic_lights_page_fragment.xml
Spot for text but left empty.
Added clock to left side - All information on clock can be overridden via bottom fragment xml
=> Added bottom fragment

app/src/main/java/com/futurice/android/reservator/view/trafficlights/RoomReservationFragment.java, app/src/main/java/com/futurice/android/reservator/view/trafficlights/TrafficLightsPageFragment.java, app/src/main/java/com/futurice/android/reservator/view/trafficlights/TrafficLightsPresenter.java, app/src/main/res/layout-v17/room_reservation_fragment.xml, app/src/main/res/values/strings.xml
=> making a reservation works now

app/src/main/java/com/futurice/android/reservator/model/Room.java, app/src/main/java/com/futurice/android/reservator/view/trafficlights/OngoingReservationFragment.java, app/src/main/java/com/futurice/android/reservator/view/trafficlights/RoomReservationFragment.java, app/src/main/java/com/futurice/android/reservator/view/trafficlights/TrafficLightsPageFragment.java, app/src/main/java/com/futurice/android/reservator/view/trafficlights/TrafficLightsPresenter.java
The logic should be correct now.
=> Make the logic of slider max lengths correct. Implement #41

app/src/main/java/com/futurice/android/reservator/model/CachedDataProxy.java, app/src/main/java/com/futurice/android/reservator/model/DataProxy.java, app/src/main/java/com/futurice/android/reservator/model/Reservation.java, app/src/main/java/com/futurice/android/reservator/model/platformcalendar/PlatformCalendarDataProxy.java, app/src/main/java/com/futurice/android/reservator/view/CalendarVisualizer.java, app/src/main/java/com/futurice/android/reservator/view/trafficlights/OngoingReservationFragment.java, app/src/main/java/com/futurice/android/reservator/view/trafficlights/RoomReservationFragment.java, app/src/main/java/com/futurice/android/reservator/view/trafficlights/TrafficLightsPresenter.java
Reservations can now be modified and deleted. Fixes issue #29
=> Reservations can now be edited. Fixes #29

app/src/main/java/com/futurice/android/reservator/view/trafficlights/TrafficLightsPresenter.java
This might fix the problem with needing to wait a long time for the UI to update (#52)
=> Added a call to refreshModel() after each model update. 

app/src/main/java/com/futurice/android/reservator/view/WeekView.java, app/src/main/res/layout/day_calendar_fragment.xml, app/src/main/res/values/attrs.xml
=> Add attrs to control number of days to show in WeekView

app/src/main/java/com/futurice/android/reservator/view/trafficlights/TrafficLightsPresenter.java
=> fix issue #55

app/src/main/java/com/futurice/android/reservator/MainActivity.java, app/src/main/java/com/futurice/android/reservator/common/LedHelper.java, app/src/main/java/com/futurice/android/reservator/common/ProDvxLedHelper.java, app/src/main/java/com/futurice/android/reservator/view/trafficlights/TrafficLightsPresenter.java, app/src/main/res/values/strings.xml
The LEDs on the ProDvx tablets now work.
=> LEDs on the ProDvx tablet now work

app/src/main/res/layout-v17/ongoing_reservation_fragment.xml, app/src/main/res/values/styles.xml
Changed size, thickness and color of progress bar when loading a reservation.
Easily configurable to match what we want.
=> Loading bar style changes

app/src/main/java/com/futurice/android/reservator/view/CalendarVisualizer.java, app/src/main/java/com/futurice/android/reservator/view/trafficlights/RoomReservationFragment.java, app/src/main/res/layout/bottom_fragment.xml, app/src/main/res/values/styles.xml
=> Updated colors

app/src/main/java/com/futurice/android/reservator/view/CalendarVisualizer.java, app/src/main/java/com/futurice/android/reservator/view/WeekView.java, app/src/main/res/values/attrs.xml
=> Customise calendar styles in xml

app/src/main/java/com/futurice/android/reservator/view/CalendarVisualizer.java, app/src/main/res/layout-v17/room_reservation_fragment.xml, app/src/main/res/layout/room_status_fragment.xml, app/src/main/res/layout/traffic_lights_page_fragment.xml, app/src/main/res/values/strings.xml
=> Updated margins and positions of calendar

app/src/main/java/com/futurice/android/reservator/MainActivity.java, app/src/main/java/com/futurice/android/reservator/view/CalendarVisualizer.java, app/src/main/java/com/futurice/android/reservator/view/trafficlights/DisconnectedFragment.java, app/src/main/java/com/futurice/android/reservator/view/trafficlights/TrafficLightsPageFragment.java, app/src/main/java/com/futurice/android/reservator/view/trafficlights/TrafficLightsPresenter.java, app/src/main/res/layout/traffic_lights_page_fragment.xml
Resolve issue #74. Only tested with emulator. Should be tested also by logging in/out of HupNet to verify that this works also with captive portals.
=> Added disconnection logic, only tested on emulator

app/src/main/java/com/futurice/android/reservator/MainActivity.java, app/src/main/java/com/futurice/android/reservator/view/trafficlights/TrafficLightsPageFragment.java, app/src/main/java/com/futurice/android/reservator/view/trafficlights/TrafficLightsPresenter.java, app/src/main/res/values/strings.xml
Should keep the screen on all the time. Also fixed a crash caused by fragment transaction asynchronizity.
=> Should keep the screen on all the time + async bugfix

app/src/main/java/com/futurice/android/reservator/model/Room.java, app/src/main/java/com/futurice/android/reservator/view/trafficlights/TrafficLightsPresenter.java
=> Prevent extending ongoing reservation over the next one

app/src/main/java/com/futurice/android/reservator/MainActivity.java, app/src/main/java/com/futurice/android/reservator/view/trafficlights/RoomReservationFragment.java
Solves issue #88. Also removes one null pointer bug introduced in the previous merge.
=> Hide the keyboard when clicking anywhere else but the keyboard. 

app/src/main/java/com/futurice/android/reservator/view/CalendarVisualizer.java, app/src/main/res/values/dimens.xml
The actual values for text sizes and padding are in values/dimens.xml. Please adjust them to your taste.
=> Changed text sizes in CalendarVisualizer from pixels to dp.

app/src/main/java/com/futurice/android/reservator/model/Room.java, app/src/main/java/com/futurice/android/reservator/view/wizard/WizardAccountSelectionFragment.java, app/src/main/java/com/futurice/android/reservator/view/wizard/WizardDefaultRoomSelectionFragment.java, app/src/main/java/com/futurice/android/reservator/view/wizard/WizardRoomSelectionFragment.java
Moved calls to activity from onCreateView to onActivityCreated.
Fixed the ConcurrentModificationException issue in Room.java that caused at least most of the crashes.
=> Fixed the bug that made the app crash on resuming.

app/src/main/res/values/styles.xml
Changed it to light blue, see if you like it before merging.
=> Changed the tentative color to light blue.

app/src/main/java/com/futurice/android/reservator/view/trafficlights/OngoingReservationFragment.java, app/src/main/res/drawable/cancel_button.xml, app/src/main/res/layout-v17/ongoing_reservation_fragment.xml, app/src/main/res/values/strings.xml
Added cancel button to the OngoingReservationFragment. It works, but the looks still might need some adjustment.
=> Cancel button

app/src/main/res/values-mul/strings.xml, app/src/main/res/values/strings.xml
Removed some references to Google in the English and three-language version.
=> Removed some references to Google.

app/src/main/java/com/futurice/android/reservator/MainActivity.java
=> Enabled full screen mode

app/src/main/java/com/futurice/android/reservator/MainActivity.java
=> Disabled volume buttons and set volume to 0

README.md, app/src/main/java/com/futurice/android/reservator/RemoteConfigActivity.java, app/src/main/java/com/futurice/android/reservator/common/PreferenceManager.java, app/src/main/java/com/futurice/android/reservator/view/trafficlights/TrafficLightsPresenter.java
Fix fix for #138 by allowing the forcing of display name to show using remote config
=> Add room displayname setting

app/build.gradle, build.gradle, gradle/wrapper/gradle-wrapper.properties
=> Building without keystore

app/src/main/AndroidManifest.xml, app/src/main/java/com/futurice/android/reservator/CheckPermissionsActivity.java, app/src/main/java/com/futurice/android/reservator/LoginActivity.java, app/src/main/java/com/futurice/android/reservator/MainActivity.java
Moved functionality from CheckPermissionsActivity and LoginActivity to MainActivity.
=> Now starts directly into MainActivity
